services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./CadnunsDev.MeusGastos.Backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - TokenSecret=${TOKEN_SECRET}
      - PasswordHashSecret=${PASSWORD_HASH_SECRET}
      - SeqServer=${SEQ_SERVER}
    ports:
      - "5000:80"
    restart: unless-stopped

  frontend:
    build:
      context: ./CadnunsDev.MeusGastos.Frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped

volumes:
  pgdata:
